// <auto-generated />
using AC_EmpManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AC_EmpManagement.Migrations
{
    [DbContext(typeof(MEmpDBContext))]
    [Migration("20220209142255_M_EmpSeed")]
    partial class M_EmpSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AC_EmpManagement.Models.MEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("DbS_Emps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 1,
                            Email = "Pishooo@parthy.com",
                            Name = "Pishooo"
                        },
                        new
                        {
                            Id = 2,
                            Department = 2,
                            Email = "qalby@parthy.com",
                            Name = "Qalby"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
